project_id = "wpurfvvpxnhwuvmimhoi"

[functions.whisper-text]
verify_jwt = false

[functions.generate-whisper-content]
verify_jwt = false

[functions.test-music-api]
verify_jwt = false

[functions.generate-asmr-session]
verify_jwt = false
